name: ci

on:
  push:
  pull_request:

jobs:
  ring-buffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S 01-ring-buffer -B 01-ring-buffer/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++
      - name: Build
        run: cmake --build 01-ring-buffer/build -j$(nproc)
      - name: Test
        run: ctest --test-dir 01-ring-buffer/build --output-on-failure

  spsc-ring-buffer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S 02-spsc-ring-buffer -B 02-spsc-ring-buffer/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++
      - name: Build
        run: cmake --build 02-spsc-ring-buffer/build -j$(nproc)
      - name: Test
        run: ctest --test-dir 02-spsc-ring-buffer/build --output-on-failure

  thread-pool:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S 03-thread-pool -B 03-thread-pool/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++
      - name: Build
        run: cmake --build 03-thread-pool/build -j$(nproc)
      - name: Test
        run: ctest --test-dir 03-thread-pool/build --output-on-failure
